[package]

name = "strsim"
version = "0.1.1"
authors = ["Danny Guo <dannyguo91@gmail.com>"]
description = """
Implementations of string similarity metrics.
Currently includes Hamming, Levenshtein, Jaro, and Jaro-Winkler.
"""
license = "MIT"
readme = "README.md"
keywords = ["string", "similarity", "Hamming", 
            "Levenshtein", "Jaro-Winkler"]
homepage = "https://github.com/dguo/strsim-rs"
repository = "https://github.com/dguo/strsim-rs"
